### ISSUE TITLE
OpenSeaDragon ViaWebGL Plugin Support for legacy tilesource

### ISSUE THREAD

**Issue by adriandarian** [thejohnhoffer/viaWebGL#12] opened 2021-08-04 01:40 UTC
I was messing around with integrating WebGL into my already made OpenSeaDragon viewer, but noticed I only needed the ability to apply textures to my tiles. I came across the ViaWebGL Plugin that does exactly what I am trying to accomplish. However this plugin has a bunch of examples of DZI files being passed as the tilesource. While my viewer runs off of the [tilesource-legacy][1] format, which is basically an array of objects where each object contains the each tile data. When I connected the plugin it said initialized and got my passed in shaders correctly, but when I press the toggle button the textures are not changing.

I have been stuck on this for a while and cannot figure out what is going on or where to the root cause is, only guesses at what could be the exact issue.

  [1]: http://openseadragon.github.io/examples/tilesource-legacy/

**Comment by iangilman** [comment] 2021-08-04 18:37
Strange! I'm not aware of the legacy tilesource handling tiles any differently than the DZI tilesource, so it should work the same. Can you provide a link to a repro?

**Comment by adriandarian** [comment] 2021-08-04 22:08
I cannot provide a link to a repo since this is company code. But let me get back with a demo mockup of this scenario.

**Comment by adriandarian** [comment] 2021-08-06 17:20
@iangilman I am unable to provide an exact demo of my setup due to a signed NDA. However, I have the OpenSeaDragon loaded and tiles assigned using the tilesource-legacy format. Then I add this code below

```javascript
$rootScope.seaGL = new openSeadragonGL(scope.osd);
$rootScope.seaGL.vShader = "plugins/openSeaDragonGL/vertex/square.glsl";
$rootScope.seaGL.fShader = "plugins/openSeaDragonGL/fragments/red.glsl";
$rootScope.seaGL.init();
```

Now I am having trouble to trigger the texture change. Our current implementation of OpenSeaDragon does not allow the use of the 

```javascript
// Add a custom button
seaGL.button({
    tooltip: 'Toggle shaders',
    prefix: this.iconPrefix,
    name: 'shade'
});
```

So I tried to trigger it by calling this method `$rootScope.seaGL.shade();`, but nothing happens.

**Comment by iangilman** [comment] 2021-08-09 18:58
I've tried an experiment with it, and here's what I'm getting: 

<img width="850" alt="image" src="https://user-images.githubusercontent.com/338989/128758795-8374faf3-22e8-4723-bfd8-dad343b72e92.png">

Here's my code:

```
<!DOCTYPE html>
<html>
<head>
    <title>OpenSeadragon Basic Demo</title>
    <script type="text/javascript" src='../../build/openseadragon/openseadragon.js'></script>
    <script type="text/javascript" src='../lib/jquery-1.9.1.min.js'></script>
    <script type='text/javascript' src='./shaders/openSeadragonGL.js'></script>
<script type='text/javascript' src='./shaders/viaWebGL.js'></script>
    <style type="text/css">

        .openseadragon1 {
            width: 800px;
            height: 600px;
        }

    </style>
</head>
<body>
    <div>
        Simple demo page to show a default OpenSeadragon viewer.
    </div>
    <div id="contentDiv" class="openseadragon1"></div>
    <script type="text/javascript">

        var tileSource = {
            type: 'legacy-image-pyramid',
            levels: [{
                url: '/test/data/iiif_2_0_sizes/full/400,/0/default.jpg',
                height: 291,
                width:  400
            }, {
                url: '/test/data/iiif_2_0_sizes/full/800,/0/default.jpg',
                height: 582,
                width:  800
            }, {
                url: '/test/data/iiif_2_0_sizes/full/1600,/0/default.jpg',
                height: 1164,
                width:  1600
            }, {
                url: '/test/data/iiif_2_0_sizes/full/3200,/0/default.jpg',
                height: 2328,
                width:  3200
            }, {
                url: '/test/data/iiif_2_0_sizes/full/6976,/0/default.jpg',
                height: 5074,
                width:  6976
            }]};

        var viewer = OpenSeadragon({
            debugMode: true,
            minZoomImageRatio: 0.0001,
            id: "contentDiv",
            prefixUrl: "../../build/openseadragon/images/",
            tileSources: tileSource,
            showNavigator:true
        });

    this.vShader = './shaders/vertex/square.glsl';
    this.fShader = './shaders/fragment/sobel3.glsl';

    var seaGL = new openSeadragonGL(viewer);
    seaGL.addHandler('tile-drawing');
    seaGL.vShader = this.vShader;
    seaGL.fShader = this.fShader;
    seaGL.init();

    </script>
</body>
</html>
```

That's intended to be run in the OpenSeadragon project under `test/demo` (it's based on basic.html). You need to add a `shaders` folder into that folder with the two plugin scripts and the two GLSL files. The legacy tiles are part of the OSD test suite. 

Interesting that it's shading part of the image but not the rest. That makes me think that there is some limitation in this plugin regarding how big of a tile it can handle or something. Counter to that theory, however, is the fact that it is doing the same thing to each tile regardless of their size. Anyway, the fact that it's working partially makes me think the issue is here in this plugin rather than in OSD; hopefully that can help narrow the search. 

As for triggering the shading, it appears to be on by default, and `shade` should toggle it off; no need for the button.

**Comment by adriandarian** [comment] 2021-08-09 19:14
I updated my codebase to follow the same setup you have shown above, but it did not change anything and no texture change appears. How would I take it apart to see what is failing? @iangilman

**Comment by iangilman** [comment] 2021-08-10 18:17
@adriandarian I see you closed this issue... does that mean you found the solution? I'm curious what it is!

**Comment by adriandarian** [comment] 2021-08-10 18:21
@iangilman I did not find a solution, but I closed the issue because the code you provided above did not work out in my current Angularjs implementation with OpenSeaDragon and came to the conclusion that this approach will most likely lead to even more issues. If there was a solution I would really like to know why even your example above won't work.

**Comment by iangilman** [comment] 2021-08-11 18:39
Did you try my example on its own without trying to integrate it into Angular? Does it at least work (e.g. produce the results I got) alone? 

Also, have you tried with DZI? I know that's not your ultimate goal, but by trying these different scenarios, you can isolate the problem area. 

I'm assuming using a format like DZI is not an option for your scenario, but I guess I should verify that that's the case... have you considered switching formats?

**Comment by adriandarian** [comment] 2021-08-17 19:08
@iangilman apologizes, I took a break to work on some other tasks for a release build. I was not able to reproduce locally. Can you share how you setup your folder structure, because my tiles with that code does not load.

Also we cannot use the DZI format because all our tiles are coming from API calls and building the legacy tile format, it would be too much rewrite to make a DZI file on the fly in the client.

**Comment by iangilman** [comment] 2021-08-18 18:24
You need to grab the code from https://github.com/openseadragon/openseadragon/ and then modify https://github.com/openseadragon/openseadragon/blob/master/test/demo/basic.html... that will put you in the right folder space. Then run the code using `grunt dev` (you also need to have done `npm install` and have Grunt installed, etc. as specified in https://github.com/openseadragon/openseadragon/blob/master/CONTRIBUTING.md). You need to add a shaders folder into the test/demo folder with the two plugin scripts and the two GLSL files. 

Let me know if that works!

**Comment by adriandarian** [comment] 2021-08-31 22:07
Resolved, the primary issue was the custom tilesource format in our project changing that I was able to meet a similar result as what ian showed above and then modified the boundaries to adjust the texturing to cover all the tiles.

**Closed as completed** 2021-08-31 22:06 UTC

**Comment by iangilman** [comment] 2021-09-01 18:42
Great! Thank you for the update :)
